### `await` on\_error (*event\_method*, _\*args_, _\*\*kwargs_)
This function is a [coroutine](https://docs.python.org/3/library/asyncio-task.html#coroutine).

The default error handler provided by the client.

By default this prints to [sys.stderr](https://docs.python.org/3/library/sys.html#sys.stderr "(in Python v3.9)") however it could be overridden to have a different implementation. Check [on_error()](discord/Event%20Reference/on_error) for more details.

